server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://54.169.25.36:3306/social_network
    url: jdbc:mysql://127.0.0.01:3306/social_network
    username: root
    password: root
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
socialnetwork:
  dbhost:
    elasticsearch-host: localhost:9200
    neo4j-connection-string: jdbc:neo4j:bolt://localhost:7687?user=neo4j,password=system,scheme=neo4j